
font_family      JetBrainsMono Nerd Font
font_size        10.0

window_padding_width 10

background            #1a1b26
foreground            #c0caf5
background_opacity    0.85 

background_blur 1

enable_audio_bell no

color0 #181818
color1 #AC4242
color2 #90A959
color3 #F4BF75
color4 #6A9FB5
color5 #AA759F
color6 #75B5AA
color7 #D8D8D8
color8 #6B6B6B
color9 #C55555
color10 #AAC474
color11 #FECA88
color12 #82B8C8
color13 #C28CB8
color14 #93D3C3
color15 #F8F8F8
