windowrule {
	name = discord
	match:class = discord

	workspace = 2
}

windowrule {
	name = telegram
	match:class = ^(org.telegram.desktop.)$

	workspace = 3
}

windowrule {
	name = btop
	match:class = ^(btop_float)$

	size = 1280 720
	center = on
	opacity = 0.95
	float = on
}

windowrule {
	name = spotify
	match:class = Spotify
	opacity = 0.85
}

windowrule {
	name = pavucontrol
	match:initial_class = ^(org.pulseaudio.pavucontrol)$

	size = 800 600
	center = on
	opacity = 0.85
	float = on
}
