windowrulev2 = workspace 2, class:(discord)
windowrulev2 = workspace 3, class:^(org.telegram.desktop.)$

windowrulev2 = float, class:^(btop_float)$
windowrulev2 = size 1280 720, class:^(btop_float)$
windowrulev2 = center, class:^(btop_float)$
windowrulev2 = opacity 0.95, class:^(btop_float)$
