windowrule {
	name = discord
	match:class = discord

	workspace = 2
}

windowrule {
	name = telegram
	match:class = ^(org.telegram.desktop.)$

	workspace = 3
}

windowrule {
	name = btop
	match:class = ^(btop_float)$

	size = 1280 720
	center = on
	opacity = 0.95
	float = on
}
